[package]
name = "hemtt"
version = "0.6.2"
authors = ["Brett Mayson <brett@mayson.io>"]
edition = "2018"

[dependencies]
armake2 = { path = "/home/brett/Documents/armake2" }
chrono = "0.4"
clap = "*"
colored = "1.8"
config = "0.9"
crossbeam = "*"
docopt = "1"
fs_extra = "*"
git2 = "0.9"
glob = "0.3"
handlebars = "1.1"
indicatif = "*"
lazy_static = "*"
linked-hash-map = "0.5"
num_cpus = "1.10"
objekt = "*"
pbr = "1.0"
question = "*"
rayon = "1.1"
regex = "1.1"
reqwest = "0.9"
rlua = "*"
self_update = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-xml-rs = "0.3"
subprocess = "0.1"
toml = "0.5"
walkdir = "2.2"
zip = { git = "https://github.com/jonpas/zip-rs", branch = "flate2", features = ["deflate"] }

[target.'cfg(windows)'.dependencies]
ansi_term = "0.12"
winreg = "0.6"
