[package]
name = "hemtt"
version = "0.6.2"
authors = ["Brett Mayson <brett@mayson.io>"]
edition = "2018"

[dependencies]
armake2 = { git = "https://github.com/synixebrett/armake2", branch = "more_pub" }
chrono = "0.4"
clap = "2.33"
colored = "1.8"
config = "0.9"
docopt = "1"
fs_extra = "1.1"
git2 = "0.9"
glob = "0.3"
handlebars = "1.1"
indicatif = { git = "https://github.com/synixebrett/indicatif", branch = "master" }
lazy_static = "1.3"
linked-hash-map = "0.5"
num_cpus = "1.10"
objekt = "0.1"
pbr = "1.0"
pf = "0.2"
question = "0.2"
rayon = "1.1"
regex = "1.1"
reqwest = "0.9"
rlua = "0.16.3"
self_update = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-xml-rs = "0.3"
subprocess = "0.1"
toml = "0.5"
walkdir = "2.2"
zip = { git = "https://github.com/jonpas/zip-rs", branch = "flate2", features = ["deflate"] }

[target.'cfg(windows)'.dependencies]
ansi_term = "0.12"
winreg = "0.6"
winapi = "0.3"