[package]
name = "hemtt"
version = "0.2.0"
authors = ["Brett <brett@bmandesigns.com>"]
edition = "2018"

[dependencies]
docopt = "1"
serde = { version = "1.0", features = ["derive"] }
colored = "1.7"
serde_json = "1.0"
reqwest = "0.9"
walkdir = "2.2"
armake2 = "0.3"

[target.'cfg(windows)'.dependencies]
winreg = "0.5"
