[package]
name = "hemtt"
version = "0.1.0"
authors = ["Brett Mayson <brett@bmandesigns.com>"]

[dependencies]
clap = "~2.32"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
reqwest = "0.9.1"
zip = "0.4"
walkdir = "2"
colored = "1.6"
