[package]
name = "hemtt-preprocessor"
version = "0.1.0"
authors = ["Brett <brett@mayson.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3"
log = "0.4"
lazy_static = "1.4"
