[package]
name = "hemtt-serde"
version = "0.1.0"
authors = ["Brett Mayson <brett@mayson.io>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
lazy_static = "1.4"

[dev-dependencies]
serde_json = "1.0"
serde-transcode = "1.1"
