name: CI

on: [push, pull_request]

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@master

      - name: Install Rust stable
        run: |
          rustup toolchain update stable
          rustup default stable
          rustup component add clippy rustfmt

      - name: Run rustfmt
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo clippy --all -- -Dwarnings

  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@master

      - name: Install Rust stable
        run: |
          rustup toolchain update stable
          rustup default stable
        
      - name: Build
        run: cargo build --all && cargo build --release

      - name: Test
        run: cargo test --all

      - uses: actions/upload-artifact@master
        with:
          name: hemtt
          path: target/release/hemtt

  build-windows:
    name: Build (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@master

      - name: Install Rust stable
        run: |
          rustup toolchain update stable
          rustup default stable
          
      - name: Install OpenSSL
        run: |
          powershell -command "Invoke-WebRequest -Uri 'http://slproweb.com/download/Win64OpenSSL-1_1_1c.msi' -OutFile openssl.msi"
          msiexec.exe /qn /i openssl.msi

      - name: Build
        env:
          OPENSSL_DIR: C:\OpenSSL-v111-Win64
        run: cargo build --all && cargo build --release

      - name: Test
        run: cargo test --all

      - uses: actions/upload-artifact@master
        with:
          name: hemtt.exe
          path: target/release/hemtt.exe
